Web/SellMe.Web/Areas/Administration/Controllers/AdsController.cs
namespace SellMe.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;
    using Common;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.InputModels.Ads;

    public class AdsController : Controller
    {
        private const int DefaultPageSize = 10;
        private const int DefaultPageNumber = 1;

        private readonly IAdsService adsService;

        public AdsController(IAdsService adsService)
        {
            this.adsService = adsService;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        public async Task<IActionResult> ForApproval(int? pageNumber)
        {
            var adsForApprovalViewModels = await adsService.GetAdsForApprovalViewModelsAsync(pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(adsForApprovalViewModels);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        public async Task<IActionResult> Approve(int adId)
        {
            var result = await adsService.ApproveAdAsync(adId);

            return Json(result);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        public async Task<IActionResult> RejectAd(int adId)
        {
            var rejectAdViewModel = await adsService.GetRejectAdBindingModelAsync(adId);

            return View(rejectAdViewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        [HttpPost]
        public async Task<IActionResult> RejectAd(RejectAdInputModel inputModel)
        {
            await adsService.CreateAdRejectionAsync(inputModel.AdId, inputModel.Comment);
            var adsForApprovalViewModels = await adsService.GetAdsForApprovalViewModelsAsync(DefaultPageNumber, DefaultPageSize);

            return RedirectToAction("ForApproval", adsForApprovalViewModels);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        public async Task<IActionResult> RejectedAds(int? pageNumber)
        {
            var rejectedAdsViewModels = await adsService.GetRejectedAdAllViewModelsAsync(pageNumber?? DefaultPageNumber, DefaultPageSize);

            return View(rejectedAdsViewModels);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        public async Task<IActionResult> AllActiveAds(int? pageNumber)
        {
            var allActiveAdViewModel = await adsService.GetAllActiveAdViewModelsAsync(pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(allActiveAdViewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [Area("Administration")]
        public async Task<IActionResult> ArchiveAd(int adId)
        {
            bool isArchived = await adsService.ArchiveAdByIdAsync(adId);

            var result = new
            {
                success = true
            };

            return Json(result);
        }
    }
}

Web/SellMe.Web/Controllers/AdsController.cs
namespace SellMe.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.BindingModels.Ads;
    using ViewModels.InputModels.Ads;

    public class AdsController : Controller
    {
        private const int DefaultPageSize = 10;
        private const int DefaultPageNumber = 1;

        private const string SuccessfullyCreatedAdMessage =
            "Your ad was successfully created. It will be reviewed by an administrator and approved as soon as possible!";

        private const string SuccessfullyUpdatedAdMessage =
            "You ad was successfully updated and moved at the top of the page!";

        private const string SuccessfullyEditedAdsMessage = "You have successfully edited this ad!";

        private const string UnSuccessfullyUpdatesAdMessage = "You can't update the given ad because it hasn't any available updates!";

        private readonly IAdsService adService;
        private readonly ISubCategoriesService subCategoriesService;


        public AdsController(IAdsService adService, ISubCategoriesService subCategoriesService)
        {
            this.adService = adService;
            this.subCategoriesService = subCategoriesService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAdInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            await adService.CreateAdAsync(inputModel);

            TempData["CreatedAd"] = SuccessfullyCreatedAdMessage;
                

            return RedirectToAction("WaitingForApproval");
        }

        public async Task<IActionResult> GetSubcategoriesAsync(int categoryId)
        {
            var subcategories = await subCategoriesService
                .GetSubcategoriesByCategoryIdAsync(categoryId);

            return Json(subcategories);
        }

        public async Task<IActionResult> AdsByCategory(AdsByCategoryInputModel inputModel)
        {
            var adsByCategoryViewModel = await adService.GetAdsByCategoryViewModelAsync(inputModel.Id, inputModel.PageNumber?? DefaultPageNumber, DefaultPageSize);

             return View(adsByCategoryViewModel);
        }

        public async Task<IActionResult> Details(AdDetailsInputModel inputModel)
        {
            var adDetailsViewModel = await adService.GetAdDetailsViewModelAsync(inputModel.Id);

            return View(adDetailsViewModel);
        }

        [Authorize]
        public async Task<IActionResult> ActiveAds(int? pageNumber)
        {
            var viewModel = await adService.GetMyActiveAdsViewModelsAsync(pageNumber?? DefaultPageNumber, DefaultPageSize);

            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ArchiveAd(int adId)
        {
            bool isArchived = await adService.ArchiveAdByIdAsync(adId);

            var result = new
            {
                success = true
            };

            return Json(result);
        }

        [Authorize]
        public async Task<IActionResult> ArchivedAds(int? pageNumber)
        {

            var archivedAdsViewModels = await adService.GetArchivedAdsViewModelsAsync(pageNumber ?? DefaultPageNumber, DefaultPageSize);


            return View(archivedAdsViewModels);
        }

        [Authorize]
        public async Task<IActionResult> ActivateAd(int adId)
        {
            bool isActivated = await adService.ActivateAdByIdAsync(adId);

            var result = new
            {
                success = true
            };

            return Json(result);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var editAdBindingModel = await adService.GetEditAdBindingModelById(id);

            return View(editAdBindingModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditAdBindingModel bindingModel)
        {
            await adService.EditAd(bindingModel.EditAdInputModel);
            TempData["SuccessfullyEditedAdsMessage"] = SuccessfullyEditedAdsMessage;

            return RedirectToAction("ActiveAds");
        }

        public async Task<IActionResult> Update(UpdateAdInputModel inputModel)
        {
            var isUpdated = await adService.UpdateAdByIdAsync(inputModel.AdId);
            if (!isUpdated)
            {
                TempData["UpdateAdMessage"] = UnSuccessfullyUpdatesAdMessage;
            }
            else
            {
                TempData["UpdateAdMessage"] = SuccessfullyUpdatedAdMessage;
            }

            return RedirectToAction("ActiveAds");
        }

        public async Task<IActionResult> AdsBySubcategory(AdsBySubcategoryInputModel inputModel)
        {
            var adsBySubcategoryViewModel = await adService.GetAdsBySubcategoryViewModelAsync(inputModel.SubcategoryId, inputModel.CategoryId, inputModel.PageNumber?? DefaultPageNumber, DefaultPageSize);

            return View(adsBySubcategoryViewModel);
        }

        public async Task<IActionResult> BySearch(AdsBySearchInputModel inputModel)
        {
            var adsBySearchViewModels = await adService.GetAdsBySearchViewModelAsync(inputModel.Search, DefaultPageNumber, DefaultPageSize);

             return View(adsBySearchViewModels);
        }

        public async Task<IActionResult> AdsByUser(string userId, int? pageNumber)
        {
            var adsByUserBindingModel = await adService.GetAdsByUserBindingModelAsync(userId, pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(adsByUserBindingModel);
        }

        public async Task<IActionResult> WaitingForApproval(int? pageNumber)
        {
            var waitingForApprovalAdsByUser = await adService.GetWaitingForApprovalByCurrentUserViewModels(pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(waitingForApprovalAdsByUser);
        }

        public async Task<IActionResult> Rejected(int? pageNumber)
        {
            var rejectedAdsByUser = await adService.GetRejectedAdByUserViewModelsAsync(pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(rejectedAdsByUser);
        }

        public async Task<IActionResult> SubmitRejectedAd(int rejectionId)
        {
            var isSucceeded = await adService.SubmitRejectedAdAsync(rejectionId);

            return Json(isSucceeded);
        }
    }
}

Web/SellMe.Web/Controllers/PromotionsController.cs
namespace SellMe.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.BindingModels.Promotions;

    public class PromotionsController : Controller
    {
        private const string SuccessfullyPromotedMessage = "You have successfully promoted this ad.";

        private readonly IPromotionsService promotionsService;

        public PromotionsController(IPromotionsService promotionsService)
        {
            this.promotionsService = promotionsService;
        }

        public async Task<IActionResult> Index(int adId)
        {
            var bindingModel = await promotionsService.GetPromotionBindingModelByAdIdAsync(adId);

            return View(bindingModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Buy(PromotionBindingModel bindingModel)
        {
            await promotionsService.CreatePromotionOrderAsync(bindingModel.PromotionInputModel.AdId,
                bindingModel.PromotionInputModel.PromotionId);

            TempData["SuccessfullyPromotedMessage"] = SuccessfullyPromotedMessage;

            return RedirectToAction("Index", new{adId = bindingModel.PromotionInputModel.AdId});
        }
    }
}

Web/SellMe.Web/Areas/Administration/Views/Ads/AllActiveAds.cshtml
@model PaginatedList<ActiveAdAllViewModel>

<h3 class="text-center">All Active Ads:</h3>
<div class="card text-center">
    <div class="card-header">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Created On</th>
                            <th scope="col">Picture</th>
                            <th scope="col">Title</th>
                            <th scope="col">Price</th>
                            <th scope="col">Details</th>
                            <th scope="col">Edit</th>
                            <th scope="col">Promote</th>
                            <th scope="col">Archive</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var ad in Model)
                        {
                            <tr class="trElm">
                                <td>
                                    @ad.CreatedOn.ToString("dd/MM/yyyy")
                                </td>
                                <td>
                                    <div>
                                        <img style="height: 40px; width: 60px" src="@ad.ImageUrl" />
                                    </div>
                                    @if (ad.IsPromoted)
                                    {
                                        <div class="mt-2">
                                            <span class="label warning">Promo</span>
                                        </div>
                                    }
                                </td>
                                <td>
                                    @ad.Title
                                </td>
                                <td>@ad.Price$</td>
                                <td>
                                    <a asp-controller="Ads" asp-action="Details" asp-route-id="@ad.Id" class="btn btn-info">Details</a>
                                </td>
                                <td>
                                    <a asp-controller="Ads" asp-action="Edit" asp-route-id="@ad.Id" class="btn btn-warning">Edit</a>
                                </td>
                                <td><a asp-controller="Promotions" asp-action="Index" asp-route-adId="@ad.Id" class="btn btn-primary">Promote</a></td>
                                <td><button type="button" value="@ad.Id" class="btn btn-danger archive">Archive</button></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="row mt-3">
    <nav class="col d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a asp-action="ActiveAds"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @prevDisabled">
                    &laquo;
                </a>
            </li>
            @if (Model.TotalPages > 1)
            {
                for (int i = 1; i <= Model.TotalPages; i++)
                {
                    if (Model.PageIndex == i)
                    {
                        <li class="page-item active">
                            <a class="page-link" asp-action="AllActiveAds"
                               asp-route-pageNumber="@i"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="AllActiveAds"
                               asp-route-pageNumber="@i"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                        </li>
                    }
                }
            }
            <li class="page-item">
                <a asp-action="AllActiveAds"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @nextDisabled">
                    &raquo;
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts
{
    <script src="~/js/archive-ad.js" asp-append-version="true"></script>
}

Web/SellMe.Web/Areas/Administration/Views/Ads/ForApproval.cshtml
@model PaginatedList<AdForApprovalViewModel>

<h3 class="text-center">Waiting for approval:</h3>
<hr class="hr-sell-me" />
<div class="card text-center">
    <div class="card-header">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Created On</th>
                            <th scope="col">Picture</th>
                            <th scope="col">Title</th>
                            <th scope="col">Price</th>
                            <th scope="col">Details</th>
                            <th scope="col">Approve</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var ad in Model)
                        {
                            <tr class="elm">
                                <td>
                                    @ad.CreatedOn.ToString("MM/dd/yyyy hh:mm tt")
                                </td>
                                <td>
                                    <div>
                                        <img style="height: 40px; width: 60px" src="@ad.ImageUrl" />
                                    </div>
                                </td>
                                <td>
                                    @ad.Title
                                </td>
                                <td>@ad.Price$</td>
                                <td>
                                    <a asp-controller="Ads" asp-action="Details" asp-route-id="@ad.Id" class="btn btn-info">Details</a>
                                </td>
                                <td>
                                    <button type="button" value="@ad.Id" class="btn btn-success approve-button">Approve</button>
                                </td>
                                <td>
                                    <a asp-area="Administration" asp-controller="Ads" asp-action="RejectAd" asp-route-adId="@ad.Id" class="btn btn-danger">Reject</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="row mt-3">
    <nav class="col d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a asp-action="ForApproval"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @prevDisabled">
                    &laquo;
                </a>
            </li>
            @if (Model.TotalPages > 1)
            {
                for (int i = 1; i <= Model.TotalPages; i++)
                {
                    if (Model.PageIndex == i)
                    {
                        <li class="page-item active">
                            <a class="page-link" asp-action="ForApproval"
                               asp-route-pageNumber="@i"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="ForApproval"
                               asp-route-pageNumber="@i"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                        </li>
                    }
                }
            }
            <li class="page-item">
                <a asp-action="ForApproval"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @nextDisabled">
                    &raquo;
                </a>
            </li>
        </ul>
    </nav>
</div>

<partial name="_ModalPartial" />

@section Scripts
{
    <script src="~/js/approve-ad.js" asp-append-version="true"></script>
}

Web/SellMe.Web/Areas/Administration/Views/Ads/RejectAd.cshtml
@model RejectAdBindingModel

    <div class="row">
        <div class="offset-2 col-8">
            <h3 class="text-center">Reject approval</h3>
            <hr class="hr-sell-me" />
            <h3 class="text-center">@Model.ViewModel.AdTitle</h3>
            <hr class="hr-sell-me" />
            <h4>Leave a comment:</h4>
            <hr class="hr-sell-me" />
            <form asp-area="Administration" asp-controller="Ads" asp-action="RejectAd" method="post">
                <div class="form-group">
                    <textarea asp-for="InputModel.Comment" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="InputModel.Comment" class="text-danger"></span>
                    <input asp-for="InputModel.AdId" type="hidden" value="@Model.ViewModel.AdId" />
                </div>
                <div class="row">
                    <div class="offset-5 col-2">
                        <button type="submit" class="btn btn-success btn-lg">Create</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

Web/SellMe.Web/Areas/Administration/Views/Ads/RejectedAds.cshtml
@model PaginatedList<RejectedAdAllViewModel>

<h3 class="text-center">Rejected ads:</h3>
<hr class="hr-sell-me" />
<div class="card text-center">
    <div class="card-header">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Created On</th>
                            <th scope="col">Picture</th>
                            <th scope="col">Title</th>
                            <th scope="col">Details</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var ad in Model)
                        {
                            <tr>
                                <td>
                                    Created On: @ad.CreatedOn.ToString("MM/dd/yyyy hh:mm tt")
                                </td>
                                <td>
                                    <div>
                                        <img style="height: 40px; width: 60px" src="@ad.ImageUrl" />
                                    </div>
                                </td>
                                <td>
                                    @ad.Title
                                </td>
                                <td>
                                    <a asp-controller="Ads" asp-action="Details" asp-route-id="@ad.Id" class="btn btn-info">Details</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<div class="row mt-3">
    <nav class="col d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a asp-action="RejectedAds"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @prevDisabled">
                    &laquo;
                </a>
            </li>
            @if (Model.TotalPages > 1)
            {
                for (int i = 1; i <= Model.TotalPages; i++)
                {
                    if (Model.PageIndex == i)
                    {
                        <li class="page-item active">
                            <a class="page-link" asp-action="RejectedAds"
                               asp-route-pageNumber="@i"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="RejectedAds"
                               asp-route-pageNumber="@i"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                        </li>
                    }
                }
            }
            <li class="page-item">
                <a asp-action="RejectedAds"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @nextDisabled">
                    &raquo;
                </a>
            </li>
        </ul>
    </nav>
</div>