Web/SellMe.Web/Controllers/AdsController.cs
namespace SellMe.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.BindingModels.Ads;
    using ViewModels.InputModels.Ads;

    public class AdsController : Controller
    {
        private const int DefaultPageSize = 10;
        private const int DefaultPageNumber = 1;

        private const string SuccessfullyCreatedAdMessage =
            "Your ad was successfully created. It will be reviewed by an administrator and approved as soon as possible!";

        private const string SuccessfullyUpdatedAdMessage =
            "You ad was successfully updated and moved at the top of the page!";

        private const string SuccessfullyEditedAdsMessage = "You have successfully edited this ad!";

        private const string UnSuccessfullyUpdatesAdMessage = "You can't update the given ad because it hasn't any available updates!";

        private readonly IAdsService adService;
        private readonly ISubCategoriesService subCategoriesService;


        public AdsController(IAdsService adService, ISubCategoriesService subCategoriesService)
        {
            this.adService = adService;
            this.subCategoriesService = subCategoriesService;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAdInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            await adService.CreateAdAsync(inputModel);

            TempData["CreatedAd"] = SuccessfullyCreatedAdMessage;
                

            return RedirectToAction("WaitingForApproval");
        }

        public async Task<IActionResult> GetSubcategoriesAsync(int categoryId)
        {
            var subcategories = await subCategoriesService
                .GetSubcategoriesByCategoryIdAsync(categoryId);

            return Json(subcategories);
        }

        public async Task<IActionResult> AdsByCategory(AdsByCategoryInputModel inputModel)
        {
            var adsByCategoryViewModel = await adService.GetAdsByCategoryViewModelAsync(inputModel.Id, inputModel.PageNumber?? DefaultPageNumber, DefaultPageSize);

             return View(adsByCategoryViewModel);
        }

        public async Task<IActionResult> Details(AdDetailsInputModel inputModel)
        {
            var adDetailsViewModel = await adService.GetAdDetailsViewModelAsync(inputModel.Id);

            return View(adDetailsViewModel);
        }

        [Authorize]
        public async Task<IActionResult> ActiveAds(int? pageNumber)
        {
            var viewModel = await adService.GetMyActiveAdsViewModelsAsync(pageNumber?? DefaultPageNumber, DefaultPageSize);

            return View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> ArchiveAd(int adId)
        {
            bool isArchived = await adService.ArchiveAdByIdAsync(adId);

            var result = new
            {
                success = true
            };

            return Json(result);
        }

        [Authorize]
        public async Task<IActionResult> ArchivedAds(int? pageNumber)
        {

            var archivedAdsViewModels = await adService.GetArchivedAdsViewModelsAsync(pageNumber ?? DefaultPageNumber, DefaultPageSize);


            return View(archivedAdsViewModels);
        }

        [Authorize]
        public async Task<IActionResult> ActivateAd(int adId)
        {
            bool isActivated = await adService.ActivateAdByIdAsync(adId);

            var result = new
            {
                success = true
            };

            return Json(result);
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var editAdBindingModel = await adService.GetEditAdBindingModelById(id);

            return View(editAdBindingModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditAdBindingModel bindingModel)
        {
            await adService.EditAd(bindingModel.EditAdInputModel);
            TempData["SuccessfullyEditedAdsMessage"] = SuccessfullyEditedAdsMessage;

            return RedirectToAction("ActiveAds");
        }

        public async Task<IActionResult> Update(UpdateAdInputModel inputModel)
        {
            var isUpdated = await adService.UpdateAdByIdAsync(inputModel.AdId);
            if (!isUpdated)
            {
                TempData["UpdateAdMessage"] = UnSuccessfullyUpdatesAdMessage;
            }
            else
            {
                TempData["UpdateAdMessage"] = SuccessfullyUpdatedAdMessage;
            }

            return RedirectToAction("ActiveAds");
        }

        public async Task<IActionResult> AdsBySubcategory(AdsBySubcategoryInputModel inputModel)
        {
            var adsBySubcategoryViewModel = await adService.GetAdsBySubcategoryViewModelAsync(inputModel.SubcategoryId, inputModel.CategoryId, inputModel.PageNumber?? DefaultPageNumber, DefaultPageSize);

            return View(adsBySubcategoryViewModel);
        }

        public async Task<IActionResult> BySearch(AdsBySearchInputModel inputModel)
        {
            var adsBySearchViewModels = await adService.GetAdsBySearchViewModelAsync(inputModel.Search, DefaultPageNumber, DefaultPageSize);

             return View(adsBySearchViewModels);
        }

        public async Task<IActionResult> AdsByUser(string userId, int? pageNumber)
        {
            var adsByUserBindingModel = await adService.GetAdsByUserBindingModelAsync(userId, pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(adsByUserBindingModel);
        }

        public async Task<IActionResult> WaitingForApproval(int? pageNumber)
        {
            var waitingForApprovalAdsByUser = await adService.GetWaitingForApprovalByCurrentUserViewModels(pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(waitingForApprovalAdsByUser);
        }

        public async Task<IActionResult> Rejected(int? pageNumber)
        {
            var rejectedAdsByUser = await adService.GetRejectedAdByUserViewModelsAsync(pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(rejectedAdsByUser);
        }

        public async Task<IActionResult> SubmitRejectedAd(int rejectionId)
        {
            var isSucceeded = await adService.SubmitRejectedAdAsync(rejectionId);

            return Json(isSucceeded);
        }
    }
}

Web/SellMe.Web/Controllers/ReviewsController.cs
namespace SellMe.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Services.Interfaces;
    using ViewModels.InputModels.Reviews;

    public class ReviewsController : Controller
    {
        private const int DefaultPageSize = 10;
        private const int DefaultPageNumber = 1;

        private readonly IReviewsService reviewsService;

        public ReviewsController(IReviewsService reviewsService)
        {
            this.reviewsService = reviewsService;
        }

        [Authorize]
        public async Task<IActionResult> ReviewsByShop(string userId, int? pageNumber)
        {
            var reviewBindingModel = await reviewsService.GetReviewsBindingModelByUserId(userId, pageNumber ?? DefaultPageNumber, DefaultPageSize);

            return View(reviewBindingModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> LeaveComment(ReviewInputModel inputModel)
        {
            if (reviewsService.CheckOwnerIdAndSellerId(inputModel.CreatorId, inputModel.OwnerId))
            {
                ModelState.AddModelError("ShopOwner", "You can't leave a review because you are the owner of the shop!");
            }

            if (!ModelState.IsValid)
            {
                var reviewBindingModel = await reviewsService.GetReviewsBindingModelByUserId(inputModel.OwnerId, DefaultPageNumber, DefaultPageSize);
                reviewBindingModel.InputModel = inputModel;
                return View("ReviewsByShop", reviewBindingModel);
            }

            await reviewsService.CreateReview(inputModel.OwnerId, inputModel.CreatorId, inputModel.Content,
                inputModel.Rating);

            return RedirectToAction("ReviewsByShop", new { userId = inputModel.OwnerId });
        }
    }
}

Web/SellMe.Web/Views/Reviews/Index.cshtml
@model ReviewsBindingModel

<link href="~/css/star-rating.css" rel="stylesheet" asp-append-version="true" />

<h3 class="text-center mb-3">@Model.OwnerUsername's shop</h3>
<div class="row">
    <div class="offset-2 col-8">
        @foreach (var review in @Model.ViewModels)
        {
            <div class="row">
                <div class="col mb-3">
                    <div class="card">
                        <div class="card-body pt-2">
                            <div class="row d-flex justify-content-between">
                                <div class="col-3" style="font-style:italic">
                                    <small>@review.Sender</small>
                                </div>
                                <div class="col-3">
                                    <div class="row mb-3">
                                        <div class="col">
                                            @for (int i = 0; i < review.Rating; i++)
                                            {
                                                <i class="fas fa-star" style="color: orange"></i>
                                            }
                                            @for (int i = 0; i < 5 - review.Rating; i++)
                                            {
                                                <i class="fas fa-star"></i>
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    @review.Content
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="row mt-3">
    <div class="offset-3 col-6">
        <form asp-controller="Reviews" asp-action="LeaveComment" method="post">
            <div class="form-group">
                <label>Write a review:</label>
                <textarea class="form-control" asp-for="@Model.InputModel.Content" rows="4"></textarea>
                <span asp-validation-for="@Model.InputModel.Content" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="@Model.InputModel.OwnerId" value="@Model.OwnerId" />
            <input type="hidden" asp-for="@Model.InputModel.CreatorId" value="@Model.SenderId" />
            <div class="row">
                <div class="col-6">
                    <div class="starrating risingstar d-flex justify-content-end flex-row-reverse">
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star5" value="5" />
                        <label for="star5" title="5 star">5</label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star4" value="4" />
                        <label for="star4" title="4 star">4</label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star3" value="3" />
                        <label for="star3" title="3 star">3</label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star2" value="2" />
                        <label for="star2" title="2 star">2</label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star1" value="1" />
                        <label for="star1" title="1 star">1</label>

                    </div>
                </div>
                <div class="offset-4 col-2">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Web/SellMe.Web/Views/Reviews/ReviewsByShop.cshtml
@model ReviewsBindingModel

<link href="~/css/star-rating.css" rel="stylesheet" asp-append-version="true" />

<div asp-validation-summary="All" class="text-danger"></div>

<h3 class="text-center mb-3">@Model.OwnerUsername's shop</h3>
<div class="card text-center mb-3">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link" asp-controller="Ads" asp-action="AdsByUser" asp-route-userId="@Model.OwnerId">Ads</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#">Reviews</a>
            </li>
        </ul>
    </div>
</div>

@for (int i = 1; i <= 5; i++)
{
<div class="row justify-content-center">
    <div class="mb-1">
        @for (int j = 0; j < i; j++)
                 {
        <i class="fas fa-star" style="color: orange"></i>
                 }
        @for (int k = 0; k < 5 - i; k++)
        {
        <i class="fas fa-star"></i>
        }
        : @Model.Votes[i - 1] votes
    </div>
</div>
}
<h5 class="text-center mb-4 mt-3">Average: @Model.AverageVote.ToString("F1") stars</h5>
<div class="row">
    <div class="offset-2 col-8">
        @foreach (var review in Model.ViewModels)
        {
        <div class="row">
            <div class="col mb-3">
                <div class="card">
                    <div class="card-body pt-2">
                        <div class="row d-flex justify-content-between">
                            <div class="col-3" style="font-style:italic">
                                <small>@review.Sender</small>
                            </div>
                            <div class="col-3">
                                <div class="row mb-3">
                                    <div class="col">
                                        @for (int i = 0; i < review.Rating; i++)
                                            {
                                        <i class="fas fa-star" style="color: orange"></i>
                                            }
                                        @for (int i = 0; i < 5 - review.Rating; i++)
                                            {
                                        <i class="fas fa-star"></i>
                                            }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                @review.Content
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }
    </div>
</div>
<div class="row mt-3">
    <div class="offset-3 col-6">
        <form asp-controller="Reviews" asp-action="LeaveComment" method="post">
            <div class="form-group">
                <label>Write a review:</label>
                <textarea class="form-control" asp-for="@Model.InputModel.Content" rows="4"></textarea>
                <span asp-validation-for="@Model.InputModel.Content" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="@Model.InputModel.OwnerId" value="@Model.OwnerId" />
            <input type="hidden" asp-for="@Model.InputModel.CreatorId" value="@Model.SenderId" />
            <div class="row">
                <div class="col-6">
                    <div class="starrating risingstar d-flex justify-content-end flex-row-reverse">
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star5" value="5" />
                        <label for="star5" title="5 star"></label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star4" value="4" />
                        <label for="star4" title="4 star"></label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star3" value="3" />
                        <label for="star3" title="3 star"></label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star2" value="2" />
                        <label for="star2" title="2 star"></label>
                        <input asp-for="@Model.InputModel.Rating" type="radio" id="star1" value="1" />
                        <label for="star1" title="1 star"></label>
                    </div>
                </div>
                <div class="offset-4 col-2">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Send</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@{
    var prevDisabled = !Model.ViewModels.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.ViewModels.HasNextPage ? "disabled" : "";
}
<div class="row">
    <nav class="col d-flex justify-content-center" aria-label="Page navigation example">
        <ul class="pagination">
            <li class="page-item">
                <a asp-action="ReviewsByShop" asp-route-userId="@Model.OwnerId"
                   asp-route-pageNumber="@(Model.ViewModels.PageIndex - 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @prevDisabled">
                    &laquo;
                </a>
            </li>
            @if (Model.ViewModels.TotalPages > 1)
            {
                for (int i = 1; i <= Model.ViewModels.TotalPages; i++)
                {
                    if (Model.ViewModels.PageIndex == i)
                    {
            <li class="page-item active">
                <a class="page-link" asp-action="ReviewsByShop" asp-route-userId="@Model.OwnerId"
                   asp-route-pageNumber="@i"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
            </li>
                    }
                    else
                    {
            <li class="page-item">
                <a class="page-link" asp-action="ReviewsByShop" asp-route-userId="@Model.OwnerId"
                   asp-route-pageNumber="@i"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
            </li>
                    }
                }
            }
            <li class="page-item">
                <a asp-action="ReviewsByShop" asp-route-userId="@Model.OwnerId"
                   asp-route-pageNumber="@(Model.ViewModels.PageIndex + 1)"
                   asp-route-currentFilter="@ViewData["CurrentFilter"]"
                   class="btn page-link btn-default @nextDisabled">
                    &raquo;
                </a>
            </li>
        </ul>
    </nav>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}