Web/SellMe.Web/ViewModels/Products/CreateProductInputModel.cs
namespace SellMe.Web.ViewModels.Products
{
    using Microsoft.AspNetCore.Http;

    public class CreateProductInputModel
    {
        public string Title { get; set; }

        public string Description { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }

        public string Subcategory { get; set; }

        public int Availability { get; set; }

        public string Condition { get; set; }

        public IFormFile AdImage { get; set; }
    }
}

Web/SellMe.Web/ViewModels/Products/CreateProductViewModel.cs
namespace SellMe.Web.ViewModels.Products
{
    using System.Collections.Generic;

    public class CreateProductViewModel
    {
        public CreateProductViewModel()
        {
            this.Categories = new HashSet<string>();
        }

        public ICollection<string> Categories { get; set; }

        public ICollection<string> Conditions { get; set; }
    }
}

Web/SellMe.Web/Controllers/ProductsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.Infrastructure;

namespace SellMe.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Linq;
    using SellMe.Services.Interfaces;
    using SellMe.Web.ViewModels.InputModels.Products;

    public class ProductsController : Controller
    {
        private readonly IProductsService productService;
       

        public ProductsController(IProductsService productService)
        {
            this.productService = productService;
        }

        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult Create(CreateAdInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            this.productService.CreateProduct(inputModel);

            return this.Redirect("/");
        }

        public IActionResult GetSubcategories(string categoryName)
        {
            var subcategories = this.productService
                .GetSubcategoriesByCategory(categoryName)
                .Select(x => new
                {
                    Name = x.Name
                })
                .ToList();

            return Json(subcategories);
        }

        public IActionResult All()
        {
            var allProductsViewModel = this.productService.GetAllProductsViewModels().ToList();

            return this.View(allProductsViewModel);
        }
    }
}

Web/SellMe.Web/Views/Products/Create.cshtml
@model SellMe.Web.ViewModels.InputModels.Products.CreateAdInputModel
@inject IProductsService ProductsService
@inject IAddressService AddressService;

@{
    var categories = this.ProductsService.GetCategoryNames();
    var conditions = this.ProductsService.GetConditionsFromDb();
    var countries = this.AddressService.GetAllCountries();
}

<div class="container-fluid">

    <form asp-controller="Products" asp-action="Create" enctype="multipart/form-data" method="post">
        <div class="row">
            <div class="col-6">
                <h2>Ad Details</h2>
                <div class="form-group">
                    <label asp-for="CreateAdDetailInputModel.Title">Title</label>
                    <input asp-for="CreateAdDetailInputModel.Title" class="form-control">
                    <span asp-validation-for="CreateAdDetailInputModel.Title" class="text-danger"></span>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label asp-for="CreateAdDetailInputModel.Category">Choose Category</label>
                        <select asp-for="CreateAdDetailInputModel.Category" class="form-control">
                            <option selected="true" disabled="disabled">--Select--</option>"
                            @foreach (var category in categories)
                            {
                                <option value="@category">@category</option>
                            }
                        </select>
                        <span asp-validation-for="CreateAdDetailInputModel.Category" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="CreateAdDetailInputModel.SubCategory">Choose Subcategory</label>
                        <select asp-for="CreateAdDetailInputModel.SubCategory" class="form-control"></select>
                        <span asp-validation-for="CreateAdDetailInputModel.SubCategory" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label asp-for="CreateAdDetailInputModel.Price">Price</label>
                        <input asp-for="CreateAdDetailInputModel.Price" type="number" class="form-control" placeholder="Enter price">
                        <span asp-validation-for="CreateAdDetailInputModel.Price" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <label asp-for="CreateAdDetailInputModel.Availability">Availability</label>
                        <input asp-for="CreateAdDetailInputModel.Availability" class="form-control" placeholder="Enter availability">
                        <span asp-validation-for="CreateAdDetailInputModel.Availability" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="CreateAdDetailInputModel.Condition">Condition</label>
                    <select asp-for="CreateAdDetailInputModel.Condition" class="form-control">
                        <option selected="true" disabled="disabled">--Select--</option>"
                        @foreach (var condition in conditions)
                        {
                            <option>@condition</option>
                        }
                    </select>
                    <span asp-validation-for="CreateAdDetailInputModel.Condition" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreateAdDetailInputModel.Description">Description</label>
                    <textarea asp-for="CreateAdDetailInputModel.Description" class="form-control" rows="5"></textarea>
                    <span asp-validation-for="CreateAdDetailInputModel.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @for (int i = 0; i < 3; i++)
                    {
                        <div class="row">
                            <div class="col-6">
                                <p><input asp-for="CreateAdDetailInputModel.Images" type="file" /> </p>
                            </div>
                            <div class="col-6">
                                <p><input asp-for="CreateAdDetailInputModel.Images" type="file" /> </p>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="col-6">
                <h2>Contact Details</h2>
                <div class="form-group">
                    <label asp-for="CreateAdAddressInputModel.Country">Country</label>
                    <select asp-for="CreateAdAddressInputModel.Country" class="form-control">
                        @foreach (var country in countries)
                        {
                            <option>@country</option>
                        }
                    </select>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="CreateAdAddressInputModel.City">City</label>
                            <input asp-for="CreateAdAddressInputModel.City" class="form-control">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="CreateAdAddressInputModel.Street">Street Address</label>
                            <input asp-for="CreateAdAddressInputModel.Street" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="CreateAdAddressInputModel.District">District</label>
                            <input asp-for="CreateAdAddressInputModel.District" class="form-control">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="CreateAdAddressInputModel.ZipCode">Zip/Postal Code</label>
                            <input asp-for="CreateAdAddressInputModel.ZipCode" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="CreateAdAddressInputModel.PhoneNumber">Phone Number</label>
                            <input asp-for="CreateAdAddressInputModel.PhoneNumber" class="form-control">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="CreateAdAddressInputModel.EmailAddress">Email Address</label>
                            <input asp-for="CreateAdAddressInputModel.EmailAddress" class="form-control">
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        $(document).ready(function () {
            $('#CreateAdDetailInputModel_Category').on("change",
                function () {
                    var categoryName = $(this).find('option:selected').val();
                    console.log(categoryName);
                    $.ajax({
                        url: "GetSubcategories",
                        type: "GET",
                        data: "categoryName=" + categoryName,
                        dataType: 'json',
                        success: function (response) {
                            $("#CreateAdDetailInputModel_SubCategory").empty(); //Reset subcategories
                            $("#CreateAdDetailInputModel_SubCategory").append("<option>--Select--</option>");
                            $.each(response, function (key, value) {
                                $("#CreateAdDetailInputModel_SubCategory").append('<option value=' + value.name + '>' + value.name + '</option>');
                                console.log(value.name);
                            });
                        }
                    });
                });
        });
    </script>
}